/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import prtype.validations;

/**
 *
 * @author ASUS
 */
public class loggin extends javax.swing.JFrame {

    /**
     * Creates new form loggin
     */
    public loggin() {
        initComponents();
        setfullscreen();
    }

    public void setfullscreen() {

        this.setResizable(false);

        Toolkit kit = Toolkit.getDefaultToolkit();

        int xsize = (int) kit.getScreenSize().getWidth();
        int ysize = (int) kit.getScreenSize().getHeight();

        int x = xsize / 2;
        int y = ysize / 2;

        this.setSize(x, y);//set size

        //moving to the center
        Dimension dimension = Toolkit.getDefaultToolkit().getScreenSize();
        int Width = this.getSize().width;
        int Height = this.getSize().height;

        int locationx = (dimension.width - Width) / 2;
        int locationy = (dimension.height - Height) / 2;

        this.setLocation(locationx, locationy);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(430, 175, 250, 35);

        jLabel1.setFont(new java.awt.Font("SimSun", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 255, 255));
        jLabel1.setText("User Name");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(272, 182, 140, 29);

        jLabel2.setFont(new java.awt.Font("SimSun", 3, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 255, 255));
        jLabel2.setText("Password");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(270, 240, 130, 29);

        jButton1.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(102, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaces/images/login.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(670, 330, 120, 50);
        getContentPane().add(jPasswordField1);
        jPasswordField1.setBounds(430, 237, 250, 34);

        jLabel3.setForeground(new java.awt.Color(153, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaces/images/14712463_610411385797937_6552385220938454496_o.jpg"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, -10, 970, 650);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String usernm = jTextField1.getText();
        String pass = jPasswordField1.getText();
        boolean success;

        validations login = new validations();
        success = login.validateUser(usernm, pass);
        System.out.println(success);

        if (success == true) {

            if (usernm.contains("manager") && pass.contains("manager123")) {
                hub a = new hub();
                a.setVisible(true);
                this.dispose();
            } else {

                if (usernm.contains("reception")) {
                    hub h = new hub();
                    h.jButton1.setEnabled(false);
                    h.jButton3.setEnabled(false);
                    h.jButton5.setEnabled(false);
                    h.jButton6.setEnabled(false);
                    h.jButton7.setEnabled(false);
                    h.jButton8.setEnabled(false);
                    h.jButton10.setEnabled(false);
                    h.jButton11.setEnabled(false);
                    h.jButton12.setEnabled(false);
                   

                    h.setVisible(true);
                    this.dispose();
               }
                else if(usernm.contains("bar&liquor")){
                     hub h = new hub();
                    h.jButton1.setEnabled(false);
                    h.jButton2.setEnabled(false);
                    h.jButton3.setEnabled(false);
                    h.jButton4.setEnabled(false);
                    h.jButton7.setEnabled(false);
                    h.jButton8.setEnabled(false);
                    h.jButton10.setEnabled(false);
                    h.jButton11.setEnabled(false);
                    h.jButton12.setEnabled(false);

                    h.setVisible(true);
                    this.dispose();
                }
                 else if(usernm.contains("restaurant")){
                     hub h = new hub();
                    h.jButton2.setEnabled(false);
                    h.jButton4.setEnabled(false);
                    h.jButton5.setEnabled(false);
                    h.jButton6.setEnabled(false);
                    h.jButton7.setEnabled(false);
                    h.jButton8.setEnabled(false);
                    h.jButton10.setEnabled(false);
                    h.jButton11.setEnabled(false);
                    h.jButton12.setEnabled(false);

                    h.setVisible(true);
                    this.dispose();
                }
                
                
            }
        } else {
            JOptionPane.showMessageDialog(null, "Invalid credentials");
            jTextField1.setText("");
            jPasswordField1.setText("");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loggin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loggin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loggin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loggin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new loggin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
